version: "3.8"

services:

  app-python3-svc:
    build: ./app-python3/
    container_name: omu-python-container
    hostname: omu-python-hostname
    working_dir: /opt/
    restart: always
    ports:
      - "8001:8080"
    volumes:
      - ./app-python3/src/:/opt/
      - ./share/:/opt/share-with-web/
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080

  web-nginx-svc:
    image: nginx:latest
    container_name: omu-nginx-container
    hostname: omu-nginx-hostname
    restart: always
    depends_on:
      - app-python3-svc
    ports:
      - 8080:80
    volumes:
      - ./web-nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./web-nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./web-nginx/contents/:/usr/share/nginx/html/
      - ./share/:/usr/share/nginx/html/share-with-python/

